### PR TITLE
Scraping unesco

### PR DESCRIPTION
**Pull request by Meden-Agan-27**
What i did:
- scraped from a website to retrieve the countries' names
- scraped Goodreads for their top-30 books for each of the 5 first countries (from the first scraping)
- added country and author to Book model
- created 118 new books in db.

Note:
- we will populate Heroku db
How to test it:
- run db:migrate and bd:seed
- test in the console that you have 118 books.

### CODE REVIEW

**Comment by Meden-Agan-27** [comment]
I changed the seeds (image and country in book show)

Please access to the books by the url (there are 118 books) 
books/:id

**Comment by madan1101** [comment]
error message: unknown attribute "country" for books
Country is missing from schema, migration

**Comment by Meden-Agan-27** [comment]
I have it in the branch... It is in my last commit 3 hours ago: 3304ee0

**Comment by Meden-Agan-27** [comment]
I think it was a pb with the "merge master". It should work now.

**Comment by sano2019** [comment]
Good style

**Pull request merged**
